---
- name: Create users
  hosts: "{{ vm_name }}"
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Make sure webadmin group exists
      ansible.builtin.group:
        name: webadmin
        state: present

    - name: Create users
      ansible.builtin.user:
        name: "{{ item['username'] }}"
        groups: "{{ item['groups'] }}"
        generate_ssh_key: true
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_my_rsa
      loop: "{{ users }}"

    - name: Sudo execution without password for webadmin users
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/webadmin
        state: present
        create: true
        mode: "0440"
        line: "%webadmin ALL=(ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s
