---
- name: Provision vm
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:

    - name: Deploy vm from template
      community.vmware.vmware_guest:
        datacenter: "{{ vcenter_datacenter }}"
        state: 'poweredon'
        folder: "{{ vcenter_folder }}"
        template: "{{ vm_template | default('vm_cs8_template') }}"
        name: "{{ vm_name }}"
        cluster: "{{ vcenter_cluster }}"
        hardware:
          memory_mb: "{{ vm_memory_mb | default(4096) }}"
          num_cpus: "{{ vm_cpus | default(2) }}"
        disk:
          - size_gb: "{{ vm_disk_size | default(30) }}"
            type: 'thin'
            datastore: "{{ datastore | default('WorkloadDatastore') }}"
        networks:
          - name: segment-sandbox-tskkn
            ip: 192.168.20.100
          # - name: "{{ vm_net_name | default('segment-sandbox-tskkn') }}"
          #   ip: "{{ vm_ip | default('192.168.95.100') }}"
            netmask: 255.255.255.0
            gateway: 192.168.20.1
            start_connected: true
            # connected: true
        customization:
          dns_servers:
            - '10.2.192.12'
          domain: 'rh.lab'
        wait_for_ip_address: 'yes'
      register: 'new_vm'
