---
- name: Provision Centos vm
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:

  - name: Deploy vm from template in vcenter
    community.vmware.vmware_guest:
      state: poweredon
      folder: "{{ vcenter_folder }}"
      template: "{{ vm_template_name }}"
      name: "{{ vm_name }}"
      cluster: "{{ vcenter_cluster }}"
      datacenter: "{{ vcenter_datacenter }}"
      hardware: 
        memory_mb: '{{ vm_memory_mb | default(4096)}}'
        num_cpus: '{{ vm_cpu | default(2)}}'
      disk:
      - size_gb: '{{ vm_disk_size | default(30) }}'
        type: 'thin'
        datastore: '{{ datastore | default(WorkloadDatastore)}}'
      networks:
      - name: "{{vm_net_name | default(vm_net_01)}}"
        ip: "{{ vm_ip | default(192.168.1.250)}}"
        netmask: 255.255.255.0
        gateway: 192.168.91.1
        start_connected: true
      customization:
        dns_servers:
        - '10.2.192.12'
        domain: 'rh.lab'
      wait_for_ip_address: 'yes' 
    register: 'new_vm'